### ISSUE TITLE
Turno

### ISSUE THREAD

**Issue by pedroventura88** [PearByteDF/app-emb#10]
Verificar se à necessidade da criação de CRUD para Turno, considerando que existem apenas 3. MATUTINO, VESPERTINO e NOTURNO.

Ideia: Criar apenas uma entidade e recuperar os dados já inputados anteriormente numa TB_TURNO.

**Comment by Silva01** [comment]
Nesse caso não precisa, podemos já deixar cadastrado no banco de dados, pois para turno acredito que não passará dessas 3 opções
